import random

nomes = [
        "Socrusto",
        "Pimpernelo",
        "Witor",
        "Samille",
        "Kennya",
        "Jilberto",
        "Giairo",
        "Creysson",
        "Hericlepton",
        "Waldisney",
        "Joleno",
        "Tsunderio",
        "Tormato",
        "Dorlange",
        "Gilderoi",
        "Miriadas",
        "Maralena",
        "Tobio",
        "Onyx",
        "Sabriel",
        "Descolado",
        "Anjelino",
        "Joender",
        "Jemerson",
        "Galerio",
        "Cavalheiro",
        "Kaylo",
        "Hendersel",
        "Kuderio",
        "Stanislau",
        "Gastoncio",
        "Deviloguia",
        "Maximo",
        "Yrlla",
        "Demetrius",
        "Kelia",
        "Sumireca",
        "Deuzivaldo",
        "Eraldonclobes",
        "Madeinusa",
        "Mijardina",
        "Jhaulismaflancyo",
        "Heubler",
        "Wonarllevyston",
        "Libertino",
        "Gosmoguete",
        "Wanslívia",
        "Hermengarda",
        "Mirella"
        ]

sobrenomes = [
        "de Andrade",
        "das Couves",
        "Spiderman",
        "Hanekawa",
        "Matador",
        "Demolidor",
        "Tobias",
        "Jacinto",
        "Bulbassauro",
        "Massimanilo",
        "Degeneris",
        "Lacroix",
        "Las Casas",
        "Brasileiro",
        "Africano",
        "Americano",
        "Alvarenga",
        "Torres",
        "Carlos",
        "Alien",
        "Flanckson",
        "Frickson",
        "Rhazyel",
        "Raimundo",
        "Misericordioso",
        "Kennemann",
        "Nemelgar",
        "Canudo",
        "Pedrosa",
        "Dratini",
        "Macharet",
        "Meira",
        "Gordo",
        "Fiorentino",
        "Castelo Branco",
        "Siqueira",
        "Gomide",
        "Zonatto",
        "Magalhaes",
        "Varella",
        "Bezerra",
        "Almirante",
        "Padeiro",
        "Glabber",
        "Globber",
        "Walquiria",
        "Quenia",
        "Lorenzoni",
        "Pedersen",
        "Moro"
        ]

nomes_completos = []
for it in nomes:
    for sn in random.sample(sobrenomes, k=4):
        nomes_completos.append(it + ' ' + sn)
print(nomes_completos)
